### ISSUE TITLE
Crash on ucinewgame

### ISSUE THREAD

**Issue by xu-shawn** [skycloudd/eccat#10]
eccat crashes with

```
thread '<unnamed>' panicked at src/search.rs:92:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    7741 abort      ./eccat
```

After running the following command:
```
go wtime 5000
ucinewgame
```

**Comment by tissatussa** [comment]
@xu-shawn is your `go` command complete and valid ? Shouldn't both `wtime` and `btime` be supplied ?

**Comment by xu-shawn** [comment]
> @xu-shawn is your `go` command complete and valid ? Shouldn't both `wtime` and `btime` be supplied ?

Also breaks with `go wtime 5000 btime 5000 winc 0 binc 0`

**Comment by skycloudd** [comment]
I think its valid, and even if it weren't valid, it just sets the time to 0 for the side you don't specify.
